import schools from './schools';

export const enumOptions = {
  school: schools,
  programOfStudy: [
    'Computer science, computer engineering, or software engineering',
    'Another engineering discipline (such as civil, electrical, mechanical, etc.)',
    'Information systems, information technology, or system administration',
    'A natural science (such as biology, chemistry, physics, etc.)',
    'Mathematics or statistics',
    'Web development or web design',
    'Business discipline (such as accounting, finance, marketing, etc.)',
    'Humanities discipline (such as literature, history, philosophy, etc.)',
    'Social science (such as anthropology, psychology, political science, etc.)',
    'Fine arts or performing arts (such as graphic design, music, studio art, etc.)',
    'Health science (such as nursing, pharmacy, radiology, etc.)',
    'Other (please specify)',
    'Undecided / No Declared Major',
    'My school does not offer majors / primary areas of study',
    'Prefer not to answer',
  ],
  gender: ['Male', 'Female', 'Non-Binary', 'Other', 'Prefer not to say'],
  pronouns: ['He/Him', 'She/Her', 'They/Them', 'Other', 'Prefer not to say'],
  ethnicity: [
    'Black/People of African Descent',
    'Arab / Middle Eastern',
    'East Asian (e.g. China, Japan, Korea)',
    'Indigenous Person of Canada',
    'Latinx',
    'Southeast Asian (e.g. Cambodia, Indonesia, Singapore)',
    'South Asian (e.g. India, Pakistan, Sri Lanka)',
    'West Asian (e.g. Afghanistan, Iran)',
    'White / People of European Descent',
    'Other',
    'Prefer not to answer',
  ],
  shirt: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
  province: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Northwest Territories',
    'Nunavut',
    'Yukon',
  ],
  countries: [
    'Canada',
    'United States of America (the)',
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas (the)',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia (Plurinational State of)',
    'Bonaire, Sint Eustatius and Saba',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'British Indian Ocean Territory (the)',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Cayman Islands (the)',
    'Central African Republic (the)',
    'Chad',
    'Chile',
    'China',
    'Christmas Island',
    'Cocos (Keeling) Islands (the)',
    'Colombia',
    'Comoros (the)',
    'Congo (the Democratic Republic of the)',
    'Congo (the)',
    'Cook Islands (the)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Curaçao',
    'Cyprus',
    'Czechia',
    "Côte d'Ivoire",
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic (the)',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Falkland Islands (the) [Malvinas]',
    'Faroe Islands (the)',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'French Polynesia',
    'French Southern Territories (the)',
    'Gabon',
    'Gambia (the)',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Heard Island and McDonald Islands',
    'Holy See (the)',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran (Islamic Republic of)',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    "Korea (the Democratic People's Republic of)",
    'Korea (the Republic of)',
    'Kuwait',
    'Kyrgyzstan',
    "Lao People's Democratic Republic (the)",
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands (the)',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia (Federated States of)',
    'Moldova (the Republic of)',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands (the)',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger (the)',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'Northern Mariana Islands (the)',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine, State of',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines (the)',
    'Pitcairn',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Republic of North Macedonia',
    'Romania',
    'Russian Federation (the)',
    'Rwanda',
    'Réunion',
    'Saint Barthélemy',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin (French part)',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten (Dutch part)',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Georgia and the South Sandwich Islands',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan (the)',
    'Suriname',
    'Svalbard and Jan Mayen',
    'Sweden',
    'Switzerland',
    'Syrian Arab Republic',
    'Taiwan',
    'Tajikistan',
    'Tanzania, United Republic of',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands (the)',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates (the)',
    'United Kingdom of Great Britain and Northern Ireland (the)',
    'United States Minor Outlying Islands (the)',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela (Bolivarian Republic of)',
    'Viet Nam',
    'Virgin Islands (British)',
    'Virgin Islands (U.S.)',
    'Wallis and Futuna',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Åland Islands',
  ],
  levelOfStudy: [
    'Secondary / High School',
    'Undergraduate Year 1',
    'Undergraduate Year 2',
    'Undergraduate Year 3+',
    'Graduate School (Masters, Professional, Doctoral, etc)',
    'Code School / Bootcamp',
    'Other Vocational / Trade Program or Apprenticeship',
    'Post Doctorate',
    'Other',
    "I'm not currently a student",
    'Prefer not to answer',
  ],
  hackathonsAttended: ['1-3', '4-6', '7-9', '10+'],
  requestedWorkshops: [
    'APIs 101',
    'Basics of Python',
    'Building a Cloud-Connected AR/VR App',
    'Communicating Tech to Executives and Diverse Stakeholders',
    'Crafting the Perfect Pitch',
    'Data and Analytics',
    'Getting your Dream Job',
    'Introduction to Computer Vision',
    'Intro to Git/GitHub',
    'Intro to React',
    'Networking 101 For Students',
    'Resume Review',
    'Starting your Startup',
    'SQL for Absolute Beginners',
    'UI/UX for Beginners',
    'What is a Single-page Application (SPA)?',
  ],
  emergencyContactRelationship: [
    'Parent',
    'Grandparent',
    'Legal guardian',
    'Sibling',
    'Other family member',
    'Friend',
    'Other',
  ],
  dietaryRestrictions: [
    'Vegetarian',
    'Vegan',
    'Celiac Disease',
    'Kosher',
    'Halal',
    'Allergies / Other',
  ],
};
